# generate a github action to lint the code

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: "Run linters"
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.8.0
          run_install: |
            - recursive: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Lint Action
        uses: wearerequired/lint-action@v2.3.0
        with:
          eslint: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
